# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev94+g8ee4968.d20221127"
__version_tuple__ = version_tuple = (0, 1, "dev94", "g8ee4968.d20221127")
