# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev34+g84017c6.d20221008'
__version_tuple__ = version_tuple = (0, 1, 'dev34', 'g84017c6.d20221008')
